<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<ShadowCopyReferences>false</ShadowCopyReferences>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Testcontainers.MySql" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="MySql.EntityFrameworkCore" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="Moq.Dapper" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\UnpakSipaksi.Modules.PotensiKetercapaianLuaranDijanjikan.Application\UnpakSipaksi.Modules.PotensiKetercapaianLuaranDijanjikan.Application.csproj" />
		<ProjectReference Include="..\UnpakSipaksi.Modules.PotensiKetercapaianLuaranDijanjikan.Domain\UnpakSipaksi.Modules.PotensiKetercapaianLuaranDijanjikan.Domain.csproj" />
		<ProjectReference Include="..\UnpakSipaksi.Modules.PotensiKetercapaianLuaranDijanjikan.Infrastructure\UnpakSipaksi.Modules.PotensiKetercapaianLuaranDijanjikan.Infrastructure.csproj" />
		<ProjectReference Include="..\UnpakSipaksi\UnpakSipaksi.csproj" />
		<!-- <None Include="Seed\init.sql" CopyToOutputDirectory="Always" /> -->
	</ItemGroup>
</Project>
