<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Microsoft Packages -->
    <PackageVersion Include="DotNet.Testcontainers" Version="1.6.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.9" />
    <!-- <PackageVersion Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" /> -->
    <!--  <PackageVersion Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
		<PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.3" /> -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <!-- MySQL / EF Core Provider -->
    <PackageVersion Include="MySql.EntityFrameworkCore" Version="9.0.6" />
    <PackageVersion Include="MySqlConnector" Version="2.4.0" />
    <!-- Logging -->
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <!-- API Docs -->
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.4" />
    <!-- JSON -->
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.Text.Json" Version="9.0.9" />
    <!-- ORM & CQRS -->
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="MediatR" Version="13.0.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <!-- Redis -->
    <!-- <PackageVersion Include="StackExchange.Redis" Version="2.8.24" /> -->
    <!-- MinIO -->
    <PackageVersion Include="Minio.AspNetCore" Version="6.0.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="FluentAssertions" Version="8.3.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Testcontainers" Version="4.7.0" />
    <PackageVersion Include="Testcontainers.MariaDb" Version="4.7.0" />
    <PackageVersion Include="Testcontainers.MySql" Version="4.7.0" />
    <PackageVersion Include="xunit" Version="2.5.3" />
    <PackageVersion Include="xunit.extensibility.core" Version="2.5.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.3" />
	<PackageVersion Include="Moq.Dapper" Version="1.0.7" />
  </ItemGroup>
</Project>